<?php

/**
 * @file
 * Contains node_reference_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function node_reference_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the node_reference_block module.
    case 'help.page.node_reference_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add a block with a Node Reference and view setting') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function node_reference_block_theme() {
  $theme = [];

  return $theme;
}
